import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demoqa.com/');
  await expect(page).toHaveURL('https://demoqa.com/');
  await page.locator('.card-up').first().click();
  await page.locator('span').filter({ hasText: 'Elements' }).locator('div').nth(2).click();
  await page.locator('span').filter({ hasText: 'Forms' }).locator('div').first().click();
  await page.getByText('Practice Form').click();
  //await expect(page.getByText('Practice Form')).toBeVisible();
  await page.getByPlaceholder('First Name').click();
  await page.getByPlaceholder('First Name').fill('Gjore');
  await expect(page.getByPlaceholder('First Name')).toHaveValue('Gjore');
  await page.getByPlaceholder('First Name').press('Tab');
  await page.getByPlaceholder('Last Name').fill('Zaharchev');
  await expect(page.getByPlaceholder('Last Name')).toHaveValue('Zaharchev');
  await page.getByPlaceholder('Last Name').press('Tab');
  await page.getByPlaceholder('name@example.com').fill('gjore.zaharchev@gmail.com');
  await expect(page.getByPlaceholder('name@example.com')).toHaveValue('gjore.zaharchev@gmail.com');
  await page.getByPlaceholder('name@example.com').press('Tab');
  await page.getByText('Male', { exact: true }).click();
  await expect(page.getByRole('radio', { name: 'Male', exact: true })).toBeChecked();
  // await expect(page.getByLabel('Male')).toBeChecked();
  await page.getByPlaceholder('Mobile Number').click();
  await page.getByPlaceholder('Mobile Number').fill('1234567890');
  await expect(page.getByPlaceholder('Mobile Number')).toHaveValue('1234567890');
  await page.locator('#dateOfBirth-wrapper div').filter({ hasText: 'Date of Birth' }).click();
  await page.locator('.subjects-auto-complete__value-container').click();
  await page.locator('#subjectsInput').fill('ma');
  await page.getByText('Maths', { exact: true }).click();
  await page.locator('#subjectsInput').fill('a');
  await page.getByText('Accounting', { exact: true }).click();
  await page.getByText('MathsAccounting').click();
  await page.getByText('MathsAccounting').click();
  await page.getByText('Sports').click();
  await expect(page.locator('#hobbies-checkbox-1')).toBeChecked();
 // await expect(page.getByText('Sports')).toHaveAttribute('class', /active/);
  await page.getByText('Reading').click();
  await expect(page.locator('#hobbies-checkbox-2')).toBeChecked();
  //await expect(page.getByText('Reading')).toHaveAttribute('class', /active/);
  await page.getByText('Music').click();
  await expect(page.locator('#hobbies-checkbox-3')).toBeChecked();
 // await expect(page.getByText('Music')).toHaveAttribute('class', /active/);
  await page.getByPlaceholder('Current Address').click();
  await page.getByPlaceholder('Current Address').fill('a');
  await expect(page.getByPlaceholder('Current Address')).toHaveValue('a');
  await page.getByText('Select State').click();
  await page.getByText('NCR', { exact: true }).click();
  //await expect(page.getByRole('option', { name: 'NCR' })).toBeVisible();
  //await page.getByText('NCR', { exact: true }).first().click();
  //await expect(page.getByText('NCR')).toBeVisible();
  await page.getByText('Select City').click();
  await page.getByText('Delhi', { exact: true }).click();
  //await expect(page.getByText('Delhi', { exact: true }).first()).toBeVisible();
  //await expect(page.getByText('Delhi')).toBeVisible();
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.locator('tbody')).toContainText('Gjore Zaharchev');
  await page.getByRole('button', { name: 'Close' }).click({ force: true });
});